# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
# Inserts a blank line between shell prompts

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[󱓞  ](bold blue)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[󱗗 󱗗](bold yellow)'


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


# Use custom format
format = '''
  ┌───────────────────>]$custom.home_icon
[[│](bold blue)$directory$rust$package
[ └─>] '''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Set 'foo' as custom color palette
palette = 'foo'

# Define custom colors
[palettes.foo]
# Overwrite existing color
blue = '21'
# Define new color
mustard = '#af8700'

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style)"

[git_branch]
format = " [$symbol$branch]($style) "
symbol = " "
style = "bold underline yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "[ ](bold dimmed red) "
ahead = "[ ×${count}](blink dimmed blue) "
behind = "[ ×${count}](blink bright-white) "
diverged = " [ ×${ahead_count}  ×${behind_count}](bright italic white) "
untracked = "[ x${count}](italic dimmed green) "
stashed = " [ ](dimmed purple) "
modified = " [ ×${count}](blink bold blue) "
staged = " [ ×${count}](dimmed italic green) "
renamed = " [ ×${count}](italic dimmed purple) "
deleted = " [ ×${count}](dimmed italic red) "
format = "$all_status$ahead_behind"

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true


[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

# Custom module to show icon in home directory
[custom.home_icon]
description = "Show icon in home directory"
command = "echo   ' 🏡'"
when = "test $(pwd) = $HOME"

